#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
autoload -Uz promptinit
promptinit
#prompt paradox
prompt sorin

# Customize to your needs...
export PATH=$HOME/bin:$PATH
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$HOME/.embulk/bin:$PATH"
export PATH=$HOME/go/bin:$PATH

# see: https://unix.stackexchange.com/questions/273861/unlimited-history-in-zsh
export HISTSIZE=10000000
export SAVEHIST=10000000

alias ga="git add"
alias gp="git pull"
alias gc="git commit"
alias gs="git status -sb"
alias gd="git diff"
alias gdc="git diff --cached"

## peco
# see: http://qiita.com/kp_ohnishi/items/3009e2083831af3a7c5c
# see: http://qiita.com/wada811/items/78b14181a4de0fd5b497
function peco-select-history() {
    local tac
    if which tac > /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi
    BUFFER=$(history -n 1 | eval $tac | awk '!a[$0]++' | peco --query "$LBUFFER")
    CURSOR=$#BUFFER
    # zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history
# source <(kubectl completion zsh)
# source <(minikube completion zsh)

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="/Users/yuokada/.sdkman"
# [[ -s "/Users/yuokada/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/yuokada/.sdkman/bin/sdkman-init.sh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /Users/yuokada/.asdf/shims/terraform terraform

# For asdf
. $(brew --prefix asdf)/libexec/asdf.sh
fpath=(
  $(brew --prefix asdf)/etc/bash_completion.d
  $fpath
)
autoload -Uz compinit && compinit

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# AWS CDK
alias cdk1="npx aws-cdk@1.x"
alias cdk="npx aws-cdk@2.x"

# Poetry
export PIPENV_VENV_IN_PROJECT=1
